struct proc_dir_entry 
{ 
    ... 
    const char *name; 
    mode_t mode; 
    ... 
    uid_t uid; 
    gid_t gid; 
    ... 
    const struct file_operations *proc_fops; 
    ... 
    read_proc_t *read_proc; 
    write_proc_t *write_proc; 
    ... 
};
